name: Publish Docker Image

on:
  push:
    branches:
      - "*"

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: code041/npm_publish
        uses: code041/npm_publish_action@1.0.8
        with:
          token: ${{ secrets.NPM_REGISTRY_TOKEN }}
          organization: 'code041'
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: code041/docker_publish
        uses: code041/docker_publish_action@1.0.1
        with:
          token: ${{ secrets.NPM_REGISTRY_TOKEN }}
          registry: ghcr.io
          image_name: ${{ github.repository }}